### ISSUE TITLE
WTF renderer?

### ISSUE THREAD

**Issue by joshbrew** [joshbrew/webgpujs#1]
So I'm working on generalizing the API and making it easier to share bindings/buffers between several shaders etc. before I do more rigorous testing on the rendering capabilities and other things, but right now I've broken the rendering on the 'borked' branch. 

It's the shader.ts file, and for some reason after encapsulating all the buffer info into these bufferGroup objects, the triangle is not rendering in the examplets.js file. The compute shaders are just fine even though they're using a lot more complicated buffer checks so I think this is VBO related instead which is a separate step. You can run this by calling `npm run example` from the main folder after installing tinybuild (my homebrew esbuild dev tool) via `npm i -g tinybuild`. 

Everything seems to set up, buffer, and execute correctly but there's no triangle showing up. Swapping between shader.ts and shaderworks.ts (the main branch file) in pipeline.ts restores the triangle once you restart the example. By direct file comparison I am just not seeing the obvious here, it's gotta be one tiny reference somewhere. I'm so confused after 2 days of not fixing it. And I'm so mad I made an issue about it in this echo chamber lol.

Also, I don't really care if this stays AGPL if anyone has serious interest in using it but finds that to be a barrier (people make a bigger deal out of it than it really is), I can swap to Apache or MIT after this matures more fully. Same applies for the rest of my libraries, I just encourage public domain contributions otherwise. 

Anyway, if anyone sees this and cares to see this get done, halp! Else if I fix it spontaneously (probably as soon as I quit whining) this'll be deleted.

**Comment by joshbrew** [comment]
I'm still stumped, it's a scoping issue. The code is on main branch now as I improved a ton of other stuff, if I can fix the renderer I can test the textures and move on

**Comment by ebudai** [comment]
I took a stab at a solution to this, but I confess I don't know all this well enough to work it out.  I did find another project with working rendering: https://github.com/AmesingFlank/taichi.js

**Comment by joshbrew** [comment]
I am coming back to this every other week and trying, the rendering worked till I scoped things into the bufferGroups so it's gotta be some dumb issue with that but they're really hard to find. The render seems to execute OK just doesn't actually show up. The computes work fine though, we'll get there as I am eager to make the shader combining work :-)

In the example, you can swap which shader.ts is imported, one works but the newest version still won't render

**Comment by joshbrew** [comment]
BTW this taichi library is awesome. I'm mainly doing this to learn as well but also to be extremely lazy writing shader pipelines if I get the whole thing going as we can split and combine data structures from as many shaders as we want far as I can tell, so there's full on GPU programs you can write that way. GPT did all the regex haha, I'm not that insane.

**Comment by ebudai** [comment]
I found this project looking for the ability to do *just that*.

**Comment by joshbrew** [comment]
It's fixed, it was the dumbest fkn problem, I didn't call device.queue.submit() on the render pass. Now onto texture and multi shader testing, biggest thing I want to have working are the storage textures which I'll show with a boids demo. We are almost there now, when this is all done this should be one of the most flexible ways to work with browser webgpu.
