### ISSUE TITLE
Texture not appearing

### ISSUE THREAD

**Issue by joshbrew** [joshbrew/webgpujs#2]
2 of us spent a week trying to figure out why textures won't render. Everything seems fine in the render stack and the render loop, and the first two examples work fine, so IDK still. Once regular texture support works then I'll test alongside storage textures, then I'll test instancing and dynamic shader chaining (which is coded out just not fully tested) which should complete this library.

**Comment by joshbrew** [comment]
This issue still persists after another couple weeks of looking into this issue. ¯\_(ツ)_/¯ It's obviously some kind of buffering issue since the transpilation is flawless. This is holding me up from finishing the entire shader loop atm as I can't verify what exactly is wrong.

**Comment by joshbrew** [comment]
¯_(ツ)_/¯

**Comment by Jman0519** [comment]
@joshbrew perhaps some outside set of eyes would help. I can take a look might go faster if you can talk me through what is happening first and how to recreate the issue.

**Comment by joshbrew** [comment]
So I just found a glaring error after finally looking at the shader code and I am doing essentially output.position = uniform * output.position due to a stupid oversight. Let me check that

**Comment by joshbrew** [comment]
Okay something is kind of showing up now

So okay here is my shorthand input (I did not document this whatsoever yet) on the latest push just a minute ago.

```js


//texture https://webgpu.github.io/webgpu-samples/samples/texturedCube
function cubeExampleVert( 
    modelViewProjectionMatrix='mat4x4<f32>'
) {
    position = modelViewProjectionMatrix * vertexIn; //alternatively we could use a builtInUniform to transform the projection matrix with the timestamp increment
    uv = uvIn;
    vertex = 0.5 * (vertexIn + vec4f(1,1,1,1));
}

function cubeExampleFrag() {
    return textureSample(image, imgSampler, uv) * position;
}

```


which results in 

```wgsl

//Bindings (data passed to/from CPU) 
struct UniformsStruct {
    modelViewProjectionMatrix: mat4x4<f32>,
};

@group(0) @binding(0) var<uniform> uniforms: UniformsStruct;



struct Vertex {
    
    @builtin(position) position: vec4<f32>, //pixel location
    //uploaded vertices from CPU, in interleaved format

    @location(0) vertex: vec4<f32>,
    @location(1) color: vec4<f32>, 
    @location(2) uv: vec2<f32>,
    @location(3) normal: vec3<f32>
};

@vertex
fn vtx_main(
    @builtin(vertex_index) vertexIndex : u32,   //current vertex
    @builtin(instance_index) instanceIndex: u32, //current instance
    @location(0) vertexIn: vec4<f32>, 
    @location(1) colorIn: vec4<f32>,
    @location(2) uvIn: vec2<f32>,
    @location(3) normalIn: vec3<f32>
) -> Vertex {
    var pixel: Vertex;
    pixel.position = uniforms.modelViewProjectionMatrix * vertexIn;
    pixel.uv = uvIn;
    pixel.vertex = 0.5 * (vertexIn + vec4f(1, 1, 1, 1));
    return pixel; 

}

```

```wgsl

//Bindings (data passed to/from CPU) 
@group(0) @binding(1) var image: texture_2d<f32>;
@group(0) @binding(2) var imgSampler: sampler;



struct Vertex {
    
    @builtin(position) position: vec4<f32>, //pixel location
    //uploaded vertices from CPU, in interleaved format

    @location(0) vertex: vec4<f32>,
    @location(1) color: vec4<f32>, 
    @location(2) uv: vec2<f32>,
    @location(3) normal: vec3<f32>
};

@fragment
fn frag_main(
    pixel: Vertex,
    @builtin(front_facing) is_front: bool,   //true when current fragment is on front-facing primitive
    @builtin(sample_index) sampleIndex: u32, //sample index for the current fragment
    @builtin(sample_mask) sampleMask: u32   //contains a bitmask indicating which samples in this fragment are covered by the primitive being rendered
) -> @location(0) vec4<f32> {
    return textureSample(image, imgSampler, pixel.uv) * pixel.position;
}

```


and this should basically match the official example minus some differences in boilerplate naming (which I might just go ahead and match to make it as familiar as possible): https://webgpu.github.io/webgpu-samples/samples/texturedCube#../../shaders/basic.vert.wgsl

```wgsl
struct Uniforms {
  modelViewProjectionMatrix : mat4x4<f32>,
}
@binding(0) @group(0) var<uniform> uniforms : Uniforms;

struct VertexOutput {
  @builtin(position) Position : vec4<f32>,
  @location(0) fragUV : vec2<f32>,
  @location(1) fragPosition: vec4<f32>,
}

@vertex
fn main(
  @location(0) position : vec4<f32>,
  @location(1) uv : vec2<f32>
) -> VertexOutput {
  var output : VertexOutput;
  output.Position = uniforms.modelViewProjectionMatrix * position;
  output.fragUV = uv;
  output.fragPosition = 0.5 * (position + vec4(1.0, 1.0, 1.0, 1.0));
  return output;
}

```


```wgsl
@group(0) @binding(1) var mySampler: sampler;
@group(0) @binding(2) var myTexture: texture_2d<f32>;

@fragment
fn main(
  @location(0) fragUV: vec2<f32>,
  @location(1) fragPosition: vec4<f32>
) -> @location(0) vec4<f32> {
  return textureSample(myTexture, mySampler, fragUV) * fragPosition;
}

```


So I know the transpiler is good which is a monster that is only pretty much parseable by the AI that wrote it haha but the shader.ts file is basically standard boilerplate and otherwise it's just kind of making assumptions for you to make the bindgroup layouts and vertex buffers and so on which you can specify further as you need to (when I actually document all of this). It seems it might just be my shader code now or the vbo offsets.

**Comment by joshbrew** [comment]
<img width="874" alt="Capture" src="https://github.com/joshbrew/webgpujs/assets/18196383/b634b6f5-c1d4-4e79-ab8b-6937eeb860cb">

result after the shader fix is something actually rotating just not filled in correctly

**Comment by joshbrew** [comment]
<img width="473" alt="Capture" src="https://github.com/joshbrew/webgpujs/assets/18196383/de9677a2-aad1-4e6c-85a5-718baf1a8dc6">

okay commenting out the mipmap setting on the texture results in this, so the vbo is for sure bugged as it should be a rainbow cube identical to the example

**Comment by joshbrew** [comment]
<img width="571" alt="Capture" src="https://github.com/joshbrew/webgpujs/assets/18196383/bbc76b22-6f49-4a87-b986-6c2ed718cd1a">
corrected the image load too

**Comment by Jman0519** [comment]
I am fairly certain that this has to do with bit alignment/padding. There appears to be indices at 0 (rather than -1 or 1) which would only happen if values are getting padded. It does not happen on the first vertex which padding would not affect. The solution to solving this problem can be done many ways which you may choose yourself, or I can attempt a solution of my own.

**Comment by Jman0519** [comment]
It appears something about passing in the cubeIndices in examplets.js line 296 is causing the vertex structure to get unaligned. Trying to track down how this argument is being used exactly.

**Comment by Jman0519** [comment]
yes, the index buffer seems to be used in its standard sense, but the indexes you specific in the exampleCube.js is incompatible with the unique uv coordinates you specify for each vertex

**Comment by Jman0519** [comment]
Alright whole issue is fixed, comment out the index buffer on line 296 (mixes up the order of the vertices and number of vertices), and remove the multiplication of position on line 228 (causes everything to look yellow).
![image](https://github.com/joshbrew/webgpujs/assets/51171267/f17980dc-debd-4296-8517-e8f5d9a3bdab)

**Comment by joshbrew** [comment]
<img width="127" alt="Capture2" src="https://github.com/joshbrew/webgpujs/assets/18196383/dd8c539a-1add-4415-bc9d-9d387d9ec1b9">

yep position should have been color but I am perpetually confused by webgl naming conventions
