### ISSUE TITLE
Can I use it to calculate md5 or sha256 please?

### ISSUE THREAD

**Issue by winktool** [joshbrew/webgpujs#3]

**Comment by joshbrew** [comment]
You should be able to write the compute shaders however you like. I am still working on shader chains once I resolve these texture errors. More examples etc will happen with it as this is like pre alpha

**Comment by winktool** [comment]
Want to pay for it

**Comment by joshbrew** [comment]
https://github.com/dezmou/SHA256-WebGPU

**Comment by winktool** [comment]
love you,but i want to write ```sha256d``` or other funtions. eg:```random hex```, compare prefix between two hex

**Comment by joshbrew** [comment]
No idea how, barely touched cryptography :-)

**Comment by winktool** [comment]
I've written javascript versions of all the functions, and I'd be very grateful if I could port them directly based on your library.

**Comment by winktool** [comment]
how to write codes on your lib like ```https://github.com/benrayfield/jsutils/blob/master/src/sha256.js```?

**Comment by joshbrew** [comment]
The function inputs are uniform and array buffers based on what type you supply for a default value (you can use strings to type explicitly) then the function itself you can write including nesting subfunctions that get compiled properly (i.e. moved to where they are only declared once). Then you just call it. Only thing rn you can do to make heads or tails is look at the example compute function. Rest I gotta document. You can run it to edit the shader live and get a feel.

**Comment by winktool** [comment]
wow

**Comment by winktool** [comment]
Very much looking forward to the fact that I can write wgsl like javascript!

**Comment by joshbrew** [comment]
It will be a lot of fun once the kinks are worked out. Biggest bonus will be multiprocessing with many shaders and shared data structures as you can write buffers once and then leave em. Works for compute, vertex, and fragment and multiple combos of such.

**Comment by winktool** [comment]
This will dramatically lower the barriers to using GPUs to accelerate computation, which is a great contribution that will greatly enhance the front-end space!

**Comment by joshbrew** [comment]
Thats the dream. Clientside compute with a clean sanity layer. Raw wgsl is a rats nest I can't keep track of but this will you do it all, at least on paper. I am trying to get through difficult render tasks to support like all of webgpu implicitly but still stumped on why my texture sample is black. After that I can test a raytracing sample which covers all of it.

**Comment by winktool** [comment]
Looking forward to it, I'll keep following your progress.

**Comment by winktool** [comment]
> https://github.com/dezmou/SHA256-WebGPU

do you know how to pass hex instead of string?
